FROM golang:1.24-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/workload ./cmd/workload
COPY internal/workload ./internal/workload
RUN CGO_ENABLED=0 go build -trimpath -o /out/triovexa-workload ./cmd/workload

FROM alpine:3.22
RUN addgroup -S triovexa && adduser -S -G triovexa triovexa
COPY --from=build /out/triovexa-workload /usr/local/bin/triovexa-workload
USER triovexa
ENTRYPOINT ["triovexa-workload"]
