import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../../api'
import { Field, MutationFeedback, PageHeader, RequestState, SectionHeading, State, Status, Empty } from '../../shared/components'
import { humanize } from '../../shared/format'

type ReasoningProfile = { provider: string; base_url: string; model: string; credential_ref: string; credential_available: boolean; credential_source?: string; json_mode: boolean; restart_required?: boolean }
type GrafanaProfile = { base_url: string; credential_ref: string; credential_available: boolean; metrics_source_uid: string; logs_source_uid: string; error_rate_query: string; latency_query: string; queue_query: string; replica_query: string; logs_query: string; deploy_logs_query: string; restart_required?: boolean }
type ConnectionStatus = { reasoning: Record<string, unknown>; grafana: Record<string, unknown>; prometheus: Record<string, unknown>; alertmanager: Record<string, unknown>; loki: Record<string, unknown> }

export function Connections() {
  const result = useQuery({ queryKey: ['connections'], queryFn: () => api<ConnectionStatus>('/api/v1/connections') })
  const reasoning = useQuery({ queryKey: ['connections', 'reasoning', 'config'], queryFn: () => api<ReasoningProfile>('/api/v1/connections/reasoning/config') })
  const grafana = useQuery({ queryKey: ['connections', 'grafana', 'config'], queryFn: () => api<GrafanaProfile>('/api/v1/connections/grafana/config') })
  return <div className="standard-page"><PageHeader title="Connections" subtitle="Configure telemetry and AI integrations used by the incident workflow." />{result.isLoading ? <State title="Checking connections…" /> : result.isError ? <RequestState error={result.error} retry={() => result.refetch()} /> : result.data ? <div className="settings-list">
    <ConnectionRow name="Reasoning provider" description="Structured triage and remediation proposals" data={result.data.reasoning} testPath="reasoning" />
    <ConnectionRow name="Grafana" description="Metrics and logs used as incident evidence" data={result.data.grafana} />
    <ConnectionRow name="Prometheus" description="Workload metrics, recording rules, and alert evaluation" data={result.data.prometheus} testPath="prometheus" />
    <ConnectionRow name="Alertmanager" description="Alert routing and delivery status for the playground stack" data={result.data.alertmanager} testPath="alertmanager" />
    <ConnectionRow name="Loki" description="Centralized logs collected from Triovexa and the workload stack" data={result.data.loki} testPath="loki" />
  </div> : <Empty title="Connections unavailable" text="The server did not return integration status." />}<section className="configuration-section" aria-labelledby="connection-configuration"><SectionHeading title="Connection configuration" meta="Provider keys are encrypted before persistent storage" /><h2 id="connection-configuration" className="sr-only">Connection configuration</h2>{reasoning.isLoading || grafana.isLoading ? <State title="Loading connection configuration…" /> : reasoning.isError ? <RequestState error={reasoning.error} retry={() => reasoning.refetch()} /> : grafana.isError ? <RequestState error={grafana.error} retry={() => grafana.refetch()} /> : <div className="configuration-grid"><ReasoningConfiguration initial={reasoning.data!} /><GrafanaConfiguration initial={grafana.data!} /></div>}</section></div>
}

function ReasoningConfiguration({ initial }: { initial: ReasoningProfile }) {
  const client = useQueryClient(), [form, setForm] = useState(initial), [apiKey, setAPIKey] = useState('')
  const payload = () => ({ provider: 'openai-compatible', base_url: form.base_url, model: form.model, credential_ref: form.credential_ref || 'LLM_API_KEY', json_mode: form.json_mode, api_key: apiKey })
  const save = useMutation({ mutationFn: () => api<ReasoningProfile>('/api/v1/connections/reasoning/config', { method: 'PUT', body: JSON.stringify(payload()) }), onSuccess: (data) => { setForm(data); setAPIKey(''); client.invalidateQueries({ queryKey: ['connections'] }); client.invalidateQueries({ queryKey: ['settings'] }) } })
  const test = useMutation({ mutationFn: () => api<Record<string, unknown>>('/api/v1/connections/reasoning/test', { method: 'POST', body: JSON.stringify(payload()) }) })
  return <form className="connection-editor" onSubmit={(event) => { event.preventDefault(); save.mutate() }}><header><div><p className="eyebrow">Reasoning</p><h3>OpenAI-compatible API</h3></div><Status value={form.credential_available ? 'credential_ready' : 'credential_missing'} /></header><Field label="API base URL" hint="API root such as https://api.openai.com or another Chat Completions-compatible endpoint."><input type="url" value={form.base_url} onChange={(e) => setForm({ ...form, provider: 'openai-compatible', base_url: e.target.value })} required /></Field><Field label="Model"><input value={form.model} onChange={(e) => setForm({ ...form, provider: 'openai-compatible', model: e.target.value })} required /></Field><Field label="API key" hint={form.credential_available ? 'Leave blank to keep the encrypted key. Enter a new value to replace it.' : 'Encrypted before storage and never returned to the browser.'}><input type="password" value={apiKey} onChange={(e) => setAPIKey(e.target.value)} autoComplete="new-password" spellCheck={false} required={!form.credential_available} /></Field><label className="check-field"><input type="checkbox" checked={form.json_mode} onChange={(e) => setForm({ ...form, provider: 'openai-compatible', json_mode: e.target.checked })} /> Request provider JSON response mode</label><div className="button-row"><button className="primary" type="submit" disabled={save.isPending}>{save.isPending ? 'Activating…' : 'Save & activate'}</button><button type="button" disabled={test.isPending || (!apiKey && !form.credential_available)} onClick={() => test.mutate()}>{test.isPending ? 'Testing…' : 'Test connection'}</button></div><MutationFeedback mutation={save} success="Provider encrypted, saved, and activated. Reasoning mode is now using the configured LLM." /><MutationFeedback mutation={test} success="Provider returned valid structured JSON." /></form>
}

function GrafanaConfiguration({ initial }: { initial: GrafanaProfile }) {
  const client = useQueryClient(), [form, setForm] = useState(initial)
  const payload = () => ({ base_url: form.base_url, credential_ref: form.credential_ref, metrics_source_uid: form.metrics_source_uid, logs_source_uid: form.logs_source_uid, error_rate_query: form.error_rate_query, latency_query: form.latency_query, queue_query: form.queue_query, replica_query: form.replica_query, logs_query: form.logs_query, deploy_logs_query: form.deploy_logs_query })
  const save = useMutation({ mutationFn: () => api<GrafanaProfile>('/api/v1/connections/grafana/config', { method: 'PUT', body: JSON.stringify(payload()) }), onSuccess: (data) => { setForm(data); client.invalidateQueries({ queryKey: ['connections'] }) } })
  const test = useMutation({ mutationFn: () => api<Record<string, unknown>>('/api/v1/connections/grafana/test', { method: 'POST', body: JSON.stringify(payload()) }) })
  const preview = useMutation({ mutationFn: () => api<{ evidence: Record<string, unknown>[] }>('/api/v1/connections/grafana/preview', { method: 'POST', body: JSON.stringify(payload()) }) })
  const set = (key: keyof GrafanaProfile, value: string) => setForm({ ...form, [key]: value })
  return <form className="connection-editor" onSubmit={(event) => { event.preventDefault(); save.mutate() }}><header><div><p className="eyebrow">Observability</p><h3>Grafana onboarding</h3></div><Status value={form.credential_available ? 'credential_ready' : 'credential_missing'} /></header><Field label="Grafana URL"><input type="url" value={form.base_url} onChange={(e) => set('base_url', e.target.value)} required /></Field><Field label="Credential reference" hint="Environment variable containing a Grafana service-account token."><input value={form.credential_ref} onChange={(e) => set('credential_ref', e.target.value.toUpperCase())} pattern="[A-Z][A-Z0-9_]{1,127}" required /></Field><div className="field-pair"><Field label="Prometheus datasource UID"><input value={form.metrics_source_uid} onChange={(e) => set('metrics_source_uid', e.target.value)} required /></Field><Field label="Loki datasource UID"><input value={form.logs_source_uid} onChange={(e) => set('logs_source_uid', e.target.value)} required /></Field></div><details className="advanced-fields"><summary>Query templates</summary><Field label="Error rate query"><textarea value={form.error_rate_query} onChange={(e) => set('error_rate_query', e.target.value)} /></Field><Field label="Latency query"><textarea value={form.latency_query} onChange={(e) => set('latency_query', e.target.value)} /></Field><Field label="Queue query"><textarea value={form.queue_query} onChange={(e) => set('queue_query', e.target.value)} /></Field><Field label="Replica query"><textarea value={form.replica_query} onChange={(e) => set('replica_query', e.target.value)} /></Field><Field label="Logs query"><textarea value={form.logs_query} onChange={(e) => set('logs_query', e.target.value)} /></Field><Field label="Deploy logs query"><textarea value={form.deploy_logs_query} onChange={(e) => set('deploy_logs_query', e.target.value)} /></Field></details><div className="button-row"><button className="primary" type="submit" disabled={save.isPending}>{save.isPending ? 'Saving…' : 'Save configuration'}</button><button type="button" disabled={test.isPending} onClick={() => test.mutate()}>{test.isPending ? 'Testing…' : 'Test connection'}</button><button type="button" disabled={preview.isPending} onClick={() => preview.mutate()}>{preview.isPending ? 'Querying…' : 'Preview evidence'}</button></div><MutationFeedback mutation={save} success="Saved. Restart Triovexa to activate this Grafana profile." /><MutationFeedback mutation={test} success="Grafana connection and datasource discovery succeeded." /><MutationFeedback mutation={preview} success={`Evidence preview returned ${preview.data?.evidence?.length ?? 0} records.`} /></form>
}

function ConnectionRow({ name, description, data, testPath }: { name: string; description: string; data: Record<string, unknown>; testPath?: string }) {
  const test = useMutation({ mutationFn: () => api<Record<string, unknown>>(`/api/v1/connections/${testPath}/test`, { method: 'POST', body: '{}' }) })
  const details = Object.entries(data).filter(([key]) => key !== 'configured')
  return <section className="setting-row"><div><h2>{name}</h2><p>{description}</p></div><div className="connection-meta">{details.map(([key, value]) => value ? <span key={key}><small>{humanize(key)}</small><code>{String(value)}</code></span> : null)}</div><div className="setting-action"><Status value={data.configured ? 'connected' : 'not_configured'} />{testPath && <button onClick={() => test.mutate()} disabled={!data.configured || test.isPending}>{test.isPending ? 'Testing…' : 'Test connection'}</button>}</div>{test.isError && <p className="connection-check connection-check-error">{test.error.message}</p>}{test.data && <p className="connection-check"><Status value={test.data.status} /><span>{String(test.data.latency_ms || '—')} ms</span></p>}</section>
}
