import { ReactNode } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../../api'
import { PageHeader, RequestState, State, Status } from '../../shared/components'
import { humanize } from '../../shared/format'

export function Settings() {
  const client = useQueryClient(), result = useQuery({ queryKey: ['settings'], queryFn: () => api<Record<string, unknown>>('/api/v1/settings') })
  const update = useMutation({ mutationFn: (payload: Record<string, unknown>) => api('/api/v1/settings', { method: 'PATCH', body: JSON.stringify(payload) }), onSuccess: () => client.invalidateQueries({ queryKey: ['settings'] }) })
  const enabled = Boolean(result.data?.kill_switch_enabled)
  const runtime = (result.data?.runtime ?? {}) as Record<string, unknown>
  return <div className="standard-page"><PageHeader title="Settings" subtitle="Deployment posture, active adapters, and execution safety controls." />{result.isLoading ? <State title="Loading settings…" /> : result.isError ? <RequestState error={result.error} retry={() => result.refetch()} /> : <div className="settings-list"><SettingRow title="Deployment mode" description="Controls authentication and external endpoint policy"><span className="setting-value">{humanize(String(result.data?.deployment_mode || 'unknown'))}</span></SettingRow><SettingRow title="Environment" description="Default environment attached to operational events"><span className="setting-value">{String(result.data?.environment || 'unknown')}</span></SettingRow><SettingRow title="Reasoning mode" description="Use the configured LLM for incident reasoning. The deterministic path is reserved for development and tests."><select aria-label="Reasoning mode" value={String(runtime.reasoning || 'llm')} disabled={update.isPending} onChange={(e) => update.mutate({ reasoning_mode: e.target.value })}><option value="llm">LLM provider</option><option value="heuristic">Heuristic — development only</option></select></SettingRow><SettingRow title="Observability mode" description="Choose local workload telemetry or Grafana datasource queries."><select aria-label="Observability mode" value={String(runtime.observability || 'demo')} disabled={update.isPending} onChange={(e) => update.mutate({ observability_mode: e.target.value })}><option value="demo">Local workload</option><option value="grafana">Grafana</option></select></SettingRow><SettingRow title="Execution kill switch" description="Persistently blocks new approvals and executions."><div className="setting-action"><Status value={enabled ? 'enabled' : 'disabled'} /><button className={enabled ? '' : 'danger'} disabled={update.isPending} onClick={() => update.mutate({ enabled: !enabled })}>{enabled ? 'Disable' : 'Enable'}</button></div></SettingRow></div>}{update.isError && <RequestState error={update.error} retry={() => update.reset()} />}</div>
}

function SettingRow({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <section className="setting-row"><div><h2>{title}</h2><p>{description}</p></div><div className="setting-control">{children}</div></section> }
