import { expect, test } from '@playwright/test'

test('registers a language profile and bounded automatic grant without a raw token', async ({ page }) => {
  await page.route('**/api/v1/session', (r) => r.fulfill({ json: { user: { id: 'admin', username: 'admin', role: 'admin' } } }))
  await page.route('**/api/v1/settings', (r) => r.fulfill({ json: { deployment_mode: 'internal', environment: 'staging', runtime: { reasoning: 'llm' } } }))
  await page.route('**/api/v1/repair/repositories', (r) => r.fulfill({ json: { items: [] } }))
  await page.route('**/api/v1/repair/bindings', (r) => r.fulfill({ status: 201, json: { ID: 'python-binding' } }))
  await page.goto('/ui/settings')
  await expect(page.getByRole('heading', { name: 'Source repositories' })).toBeVisible()
  await page.getByLabel('Service', { exact: true }).fill('python-worker')
  await page.getByLabel('Environment', { exact: true }).fill('staging')
  await page.getByLabel('GitHub repository URL').fill('https://github.com/owner/python-worker')
  await page.getByLabel('Allowed source paths, comma separated').fill('src, tests, pyproject.toml')
  await page.getByLabel('GitHub credential reference').fill('env:REPAIR_GITHUB_READ_TOKEN')
  await page.getByLabel('Prebuilt sandbox image').fill('triovexa-repair-sandbox:python')
  await page.getByLabel('Required root files, comma separated').fill('pyproject.toml')
  await page.getByLabel('Protected test paths, comma separated').fill('tests')
  await page.getByLabel('Test executable in container').fill('/usr/local/bin/python')
  await page.getByLabel('Fixed test arguments (JSON)').fill('["-m","unittest","discover","-s","tests","-v"]')
  await page.getByLabel('Regression test name in failing output').fill('test_accepts_one')
  await page.getByLabel('Regression failure marker').fill('one rejected')
  await page.getByLabel('Automatically investigate incoming alerts').check()
  await page.getByLabel('Existing model campaign ID').fill('approved-campaign')
  await page.getByLabel('Grant expiry').fill('2026-10-08T18:00')
  await page.getByLabel('Maximum model requests per investigation').fill('2')
  await page.getByLabel('Publish a draft PR after the patch passes validation').check()
  const sent = page.waitForRequest((r) => r.url().endsWith('/api/v1/repair/bindings') && r.method() === 'POST')
  await page.getByRole('button', { name: 'Register repository' }).click()
  const body = (await sent).postDataJSON()
  expect(body.credential_ref).toBe('env:REPAIR_GITHUB_READ_TOKEN')
  expect(body.api_key).toBeUndefined()
  expect(body.validation_profile.test.arguments).toEqual(['-m', 'unittest', 'discover', '-s', 'tests', '-v'])
  expect(body.automation).toMatchObject({ enabled: true, campaign_id: 'approved-campaign', max_investigations: 1, max_model_requests: 2, publish_draft_pr: true })
  expect(body.automation.authorized_by).toBeUndefined()
  await expect(page.getByRole('status')).toHaveText('Repository registered.')
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
})
