import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../../api'
import { MutationFeedback, PageHeader, RequestState, SectionHeading, State, Status, SystemState } from '../../shared/components'
import { humanize } from '../../shared/format'

type PlaygroundData = { enabled: boolean; modes: string[]; state?: Record<string, unknown> }

export function Playground() {
  const client = useQueryClient()
  const result = useQuery({ queryKey: ['playground'], queryFn: () => api<PlaygroundData>('/api/v1/playground'), refetchInterval: document.visibilityState === 'visible' ? 3000 : false, retry: 1 })
  const fault = useMutation({ mutationFn: (mode: string) => api('/api/v1/playground/faults', { method: 'POST', body: JSON.stringify({ mode }) }), onSuccess: () => client.invalidateQueries({ queryKey: ['playground'] }), retry: false })
  const state = result.data?.state ?? {}
  return <div className="standard-page"><PageHeader title="Playground" subtitle="Inject bounded workload faults and watch the real alert, approval, execution, and recovery flow." />{result.isRefetchError && result.data && <SystemState kind="stale" title="Supervisor data is stale" text="The last refresh failed; controls are disabled until connectivity returns." retry={() => result.refetch()} compact />}{result.isLoading ? <State title="Connecting to workload supervisor…" /> : result.isError && !result.data ? <RequestState error={result.error} retry={() => result.refetch()} /> : !result.data?.enabled ? <SystemState kind="disconnected" title="Playground is unavailable" text="Configure WORKLOAD_CONTROL_BASE_URL to enable bounded fault controls." retry={() => result.refetch()} /> : <><section className="workload-state" aria-live="polite"><SectionHeading title="Queue worker" meta={result.isFetching ? 'Refreshing…' : 'Live supervisor state'} /><dl>{Object.entries(state).map(([key, value]) => <div key={key}><dt>{humanize(key)}</dt><dd>{typeof value === 'boolean' ? <Status value={value ? 'yes' : 'no'} /> : String(value)}</dd></div>)}</dl></section><section className="fault-controls" aria-labelledby="fault-controls-heading"><div><p className="eyebrow">Bounded controls</p><h2 id="fault-controls-heading">Fault injection</h2><p>Stall keeps producing jobs while the worker stops consuming. Restart remediation clears the fault and starts a new worker generation.</p></div><div className="fault-actions"><button className="danger" disabled={fault.isPending || result.isRefetchError} onClick={() => fault.mutate('stall')}>Inject worker stall</button><button disabled={fault.isPending || result.isRefetchError} onClick={() => fault.mutate('fail')}>Inject processing failures</button><button className="primary" disabled={fault.isPending || result.isRefetchError} onClick={() => fault.mutate('healthy')}>Restore healthy mode</button></div><MutationFeedback mutation={fault} success="Fault mode updated. Prometheus and Alertmanager will evaluate the resulting telemetry." /></section></>}</div>
}
