global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: triovexa
    static_configs:
      - targets: ["triovexa:8080"]
  - job_name: queue-workload
    static_configs:
      - targets: ["workload-supervisor:8091"]
